<?php

namespace Config;

class Url {

    public $urls = [
        'baseUrl' => '',
        'dashboard' => 'admin',
        'transaction' => 'admin/transaction',
        'transactionDownloadTemplate' => 'admin/transaction/downloadtemplate',
        'transactionDatatable' => 'admin/transaction/search',
        'transactionUpload' => 'admin/transaction/upload',
        'transactionSetUserType' => 'admin/',
        'transactionEdit' => 'admin/transaction/edit',
        'transactionDelete' => 'admin/transaction/delete',
        'transactionAdd' => 'admin/transaction/add',
        'otherReceipt' => 'admin/otherreceipt',
        'otherReceiptSearch' => 'admin/otherreceipt/search',
        'otherReceiptAdd' => 'admin/otherreceipt/add',
        'otherReceiptEdit' => 'admin/otherreceipt/edit',
        'closingBalance' => 'admin/closingbalance',
        'closingBalanceEdit' => 'admin/closingbalance/info',
        'closingBalanceUpload' => 'admin/closingbalance/upload',
        'componentAgency' => 'admin/component/agency',
        'componentAgencyAssign' => 'admin/component/agency/assign',
        'componentBlock' => 'admin/component/block',
        'componentBlockAssign' => 'admin/component/block/assign',
        'componentBudget' => 'admin/component/budget',
        'openingBalance' => 'admin/openingbalance',
        'approve' => 'admin/approve',
        'approveTransaction' => 'admin/approve/transaction',
        'approveOtherReceipt' => 'admin/approve/otherreceipt',
        'approveClosingBalance' => 'admin/approve/closingbalance',
        'approveForm' => 'admin/approve/getform',
        'approveMIS' => 'admin/approve/mis',
        'profileUpload' => 'profile/upload',
        'profile' => 'profile',
        'refund' => 'admin/transaction/refund',
        'refundDatatable' => 'admin/transaction/refund/search',
        'refundAdd' => 'admin/transaction/refund/add',
        'refundEdit' => 'admin/transaction/refund/edit',
        'allotmentAdd' => 'admin/uc/allotment/add',
        'allotmentEdit' => 'admin/uc/allotment/edit',
        'allotmentInfo' => 'admin/uc/allotment/info',
        'allotmentDelete' => 'admin/uc/allotment/delete',
        'ucSubmitInfo' => 'admin/uc/submit/info',
        'ucSubmitAdd' => 'admin/uc/submit/add',
        'ucSubmitEdit' => 'admin/uc/submit/edit',
        'ucSubmitUpload' => 'admin/uc/submit/upload',
        'mprDownload' => 'admin/reports/mpr/download',
        'abstractMprDownload' => 'admin/reports/abstractmpr/download',
        'mprUpload' => 'admin/reports/mprupload/upload',
        'mis' => 'admin/mis',
        'misAdd' => 'admin/mis/add',
        'misEdit' => 'admin/mis/edit',
        'misDelete' => 'admin/mis/delete',
        'MISUpload' => 'admin/mis/upload',
        'misDatatable' => 'admin/mis/search',
        'getBlocks' => 'admin/district/block',
        'getDistricts' => 'admin/district/fundagency',
        'misIsUploaded' => 'admin/transaction/isuploaded',
        'userAllowUpload' => 'admin/users/allowupload/update',
        'userUploadStatus' => 'admin/users/uploadstatus/update',
    ];

}
