<?php

namespace Config;

class Url {

    const BASE_URL = '';

    public array $urls = [
        'dashboard' => self::BASE_URL . 'admin',
        'transaction' => self::BASE_URL . 'admin/transaction',
        'transactionDownloadTemplate' => self::BASE_URL . 'admin/transaction/downloadtemplate',
        'transactionDatatable' => self::BASE_URL . 'admin/transaction/search',
        'transactionUpload' => self::BASE_URL . 'admin/transaction/upload',
        'transactionSetUserType' => self::BASE_URL . 'admin/',
        'transactionEdit' => self::BASE_URL . 'admin/transaction/edit',
        'transactionDelete' => self::BASE_URL . 'admin/transaction/delete',
        'transactionAdd' => self::BASE_URL . 'admin/transaction/add',
        'otherReceipt' => self::BASE_URL . 'admin/otherreceipt',
        'otherReceiptSearch' => self::BASE_URL . 'admin/otherreceipt/search',
        'otherReceiptAdd' => self::BASE_URL . 'admin/otherreceipt/add',
        'otherReceiptEdit' => self::BASE_URL . 'admin/otherreceipt/edit',
        'closingBalance' => self::BASE_URL . 'admin/closingbalance',
        'closingBalanceEdit' => self::BASE_URL . 'admin/closingbalance/info',
        'closingBalanceUpload' => self::BASE_URL . 'admin/closingbalance/upload',
        'componentAgency' => self::BASE_URL . 'admin/component/agency',
        'componentAgencyAssign' => self::BASE_URL . 'admin/component/agency/assign',
        'componentBlock' => self::BASE_URL . 'admin/component/block',
        'componentBlockAssign' => self::BASE_URL . 'admin/component/block/assign',
        'componentBudget' => self::BASE_URL . 'admin/component/budget',
        'openingBalance' => self::BASE_URL . 'admin/openingbalance',
        'approve' => self::BASE_URL . 'admin/approve',
        'approveTransaction' => self::BASE_URL . 'admin/approve/transaction',
        'approveOtherReceipt' => self::BASE_URL . 'admin/approve/otherreceipt',
        'approveClosingBalance' => self::BASE_URL . 'admin/approve/closingbalance',
        'approveForm' => self::BASE_URL . 'admin/approve/getform',
        'approveMIS' => self::BASE_URL . 'admin/approve/mis',
        'profileUpload' => 'profile/upload',
        'profile' => 'profile',
        'refund' => self::BASE_URL . 'admin/transaction/refund',
        'refundDatatable' => self::BASE_URL . 'admin/transaction/refund/search',
        'refundAdd' => self::BASE_URL . 'admin/transaction/refund/add',
        'refundEdit' => self::BASE_URL . 'admin/transaction/refund/edit',
        'allotmentAdd' => self::BASE_URL . 'admin/uc/allotment/add',
        'allotmentEdit' => self::BASE_URL . 'admin/uc/allotment/edit',
        'allotmentInfo' => self::BASE_URL . 'admin/uc/allotment/info',
        'allotmentDelete' => self::BASE_URL . 'admin/uc/allotment/delete',
        'ucSubmitInfo' => self::BASE_URL . 'admin/uc/submit/info',
        'ucSubmitAdd' => self::BASE_URL . 'admin/uc/submit/add',
        'ucSubmitEdit' => self::BASE_URL . 'admin/uc/submit/edit',
        'ucSubmitUpload' => self::BASE_URL . 'admin/uc/submit/upload',
        'mprDownload' => self::BASE_URL . 'admin/reports/mpr/download',
        'abstractMprDownload' => self::BASE_URL . 'admin/reports/abstractmpr/download',
        'mprUpload' => self::BASE_URL . 'admin/reports/mprupload/upload',
        'mis' => self::BASE_URL . 'admin/mis',
        'misAdd' => self::BASE_URL . 'admin/mis/add',
        'misEdit' => self::BASE_URL . 'admin/mis/edit',
        'misDelete' => self::BASE_URL . 'admin/mis/delete',
        'MISUpload' => self::BASE_URL . 'admin/mis/upload',
        'misDatatable' => self::BASE_URL . 'admin/mis/search',
        'getBlocks' => self::BASE_URL . 'admin/district/block',
        'getDistricts' => self::BASE_URL . 'admin/
