name: SOEV2 Deploy
on:
  push:
    branches:
      - prod
      - test
jobs:
  deploy_main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prod'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy files for main branch
      run: |
        cp -r * /${{ secrets.PROD_PATH }}/

  deploy_test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy files for test branch
      run: |
        cp -r * /${{ secrets.TEST_PATH }}/
